name: Linux .rpm installer on Python 3.9

on:
  workflow_dispatch:
  push:
    branches:
      #- main
      - dev
    tags:
        - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Linux .rpm installer on Python 3.8
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.8]
        os: [ubuntu-18.04]

    steps:
    - name: Cancel previous runs on the same branch
      if: ${{ github.ref != 'refs/heads/main' }}
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - uses: Chia-Network/actions/git-ssh-to-https@main

    - name: Cleanup any leftovers that exist from previous runs
      run: bash build_scripts/clean-runner.sh || true

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache npm
      uses: actions/cache@v3.3.1
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
                
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip
      uses: actions/cache@v3.3.1
      with:
        # Note that new runners may break this https://github.com/actions/cache/issues/292
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    # Create our own venv outside of the git directory JUST for getting the ACTUAL version so that install can't break it
    - name: Get version number
      id: version_number
      run: |
        python3 -m venv ../venv
        . ../venv/bin/activate
        pip3 install setuptools_scm
        echo "::set-output name=ECOSTAKE_INSTALLER_VERSION::$(python3 ./build_scripts/installer-version.py)"
        deactivate

    - name: Test for secrets access
      id: check_secrets
      shell: bash
      run: |
        unset HAS_SECRET
        if [ -n "$SECRET" ]; then HAS_SECRET='true' ; fi
        echo ::set-output name=HAS_SECRET::${HAS_SECRET}
      env:
        SECRET: "${{ secrets.INSTALLER_UPLOAD_SECRET }}"

      # Get the most recent release from chia-plotter-madmax
    - uses: actions/github-script@v4
      id: 'latest-madmax'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          const releases = await github.repos.listReleases({
            owner: 'Chia-Network',
            repo: 'chia-plotter-madmax',
          });
          return releases.data[0].tag_name;

    - name: Get latest madmax plotter
      run: |
        mkdir "${{ github.workspace }}/madmax"
        wget -O "${{ github.workspace }}/madmax/ecostake_plot" https://github.com/Chia-Network/chia-plotter-madmax/releases/download/${{ steps.latest-madmax.outputs.result }}/chia_plot-${{ steps.latest-madmax.outputs.result }}-x86-64
        wget -O "${{ github.workspace }}/madmax/ecostake_plot_k34" https://github.com/Chia-Network/chia-plotter-madmax/releases/download/${{ steps.latest-madmax.outputs.result }}/chia_plot_k34-${{ steps.latest-madmax.outputs.result }}-x86-64
        chmod +x "${{ github.workspace }}/madmax/ecostake_plot"
        chmod +x "${{ github.workspace }}/madmax/ecostake_plot_k34"

      # Get the most recent release from bladebit
    - uses: actions/github-script@v4
      id: 'latest-bladebit'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          const releases = await github.repos.listReleases({
            owner: 'Chia-Network',
            repo: 'bladebit',
          });
          return releases.data[0].tag_name;

    - name: Get latest bladebit plotter
      run: |
        mkdir "${{ github.workspace }}/bladebit"
        wget -O /tmp/bladebit.tar.gz https://github.com/Chia-Network/bladebit/releases/download/${{ steps.latest-bladebit.outputs.result }}/bladebit-${{ steps.latest-bladebit.outputs.result }}-centos-x86-64.tar.gz
        tar -xvzf /tmp/bladebit.tar.gz -C ${{ github.workspace }}/bladebit
        chmod +x "${{ github.workspace }}/bladebit/bladebit"
    - name: Run install script
      env:
        INSTALL_PYTHON_VERSION: ${{ matrix.python-version }}
        BUILD_VDF_CLIENT: "N"
      run: |
        sh install.sh
        
    - name: Setup Node 16.x
      uses: actions/setup-node@v2.5.0
      with:
        node-version: '16.x'

    - name: Add jq
      run: |
        sudo apt-get install -y jq

    - name: Build .rpm package
      run: |
        . ./activate
        ldd --version
        cd ./ecostake-blockchain-gui
        git status
        cd ../build_scripts
        sh build_linux_rpm.sh amd64

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Linux-Installers
        path: ${{ github.workspace }}/build_scripts/final_installer/

    - name: Create Checksums
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
      env:
        ECOSTAKE_INSTALLER_VERSION: ${{ steps.version_number.outputs.ECOSTAKE_INSTALLER_VERSION }}
      run: |
         ls ${{ github.workspace }}/build_scripts/final_installer/
         sha256sum ${{ github.workspace }}/build_scripts/final_installer/ecostake-blockchain-${ECOSTAKE_INSTALLER_VERSION}-1.x86_64.rpm > ${{ github.workspace }}/build_scripts/final_installer/ecostake-blockchain-${ECOSTAKE_INSTALLER_VERSION}-1.x86_64.rpm.sha256
         ls ${{ github.workspace }}/build_scripts/final_installer/

    - name: Get tag name
      if: startsWith(github.ref, 'refs/tags/')
      id: tag-name
      run: |
          echo "::set-output name=TAG_NAME::$(echo ${{ github.ref }} | cut -d'/' -f 3)"
          echo "::set-output name=REPO_NAME::$(echo ${{ github.repository }} | cut -d'/' -f 2)"
